@startuml graph
digraph diag {
  node [style="rounded,filled", shape=box]
  "Início" -> "O que são linguagens de programação?:4"
  "O que são linguagens de programação?:4" -> "Uso do bash:1"
  "Uso do bash:1" -> "Configuração do Ambiente:2"
  "O que são linguagens de programação?:4" -> "Makefile:4"
  "O que são linguagens de programação?:4" -> "Primeiro código:6"
  "Entrada e Saída - puts, printf, scanf:5" -> "String não é um tipo primitivo:1"
  "Primeiro código:6" -> "Clean Code - Estilo:1"
  "Primeiro código:6" -> "Clean Code - Indentação:1"
  "Primeiro código:6" -> "Manipulando tipos:1"
  "Primeiro código:6" -> "Casting e Conversão:3"
  "Primeiro código:6" -> "Operações Básicas:3"
  "TKO - Ferramenta de Testes:1" -> "Operações Básicas:3"
  "Operações Básicas:3" -> "Biblioteca matemática:2"
  "Operações Básicas:3" -> "Entrada e Saída - puts, printf, scanf:5"
  "Strings:6" -> "Lendo e escrevendo em strings sprintf e sscanf:3"
  "O que são linguagens de programação?:4" -> "TKO - Ferramenta de Testes:1"
  "Entrada e Saída - puts, printf, scanf:5" -> "Seleção Básica:10"
  "Clean Code - Estilo:1" -> "Seleção Básica:10"
  "Clean Code - Indentação:1" -> "Seleção Básica:10"
  "O que são linguagens de programação?:4" -> "Debugando:1"
  "Funções I:5" -> "Técnicas de seleção I:8"
  "Técnicas de seleção I:8" -> "Técnicas de seleção II:10"
  "Seleção Básica:10" -> "Funções I:5"
  "Funções I:5" -> "Funções II:4"
  "Seleção Básica:10" -> "While:4"
  "While:4" -> "for:8"
  "Seleção Básica:10" -> "Números Aleatórios:3"
  "Strings:6" -> "IO: argc e argv:2"
  "for:8" -> "Array Iniciante:4"
  "Funções I:5" -> "Array Iniciante:4"
  "Array Iniciante:4" -> "Array avançado:4"
  "Array avançado:4" -> "Array Expert:6"
  "Array avançado:4" -> "Strings:6"
  "Strings:6" -> "Strings II:3"
  "Ponteiros:1" -> "Strings II:3"
  "Funções II:4" -> "Ponteiros:1"
  "Funções I:5" -> "Structs:1"
  "Array Iniciante:4" -> "Matrizes:2"
  "Matrizes:2" -> "Técnicas em matrizes:1"
  "Structs Advanced:2" -> "Técnicas em matrizes:1"
  "Ponteiros:1" -> "Structs Advanced:2"
  "Array Iniciante:4" -> "Structs Advanced:2"
  "Structs:1" -> "Structs Advanced:2"
  "O que são linguagens de programação?:4" [fillcolor=lime]
  "Uso do bash:1" [fillcolor=pink]
  "Configuração do Ambiente:2" [fillcolor=pink]
  "Makefile:4" [fillcolor=pink]
  "Primeiro código:6" [fillcolor=lime]
  "String não é um tipo primitivo:1" [fillcolor=lime]
  "Clean Code - Estilo:1" [fillcolor=lime]
  "Clean Code - Indentação:1" [fillcolor=lime]
  "Manipulando tipos:1" [fillcolor=pink]
  "Casting e Conversão:3" [fillcolor=pink]
  "Operações Básicas:3" [fillcolor=lime]
  "Biblioteca matemática:2" [fillcolor=pink]
  "Entrada e Saída - puts, printf, scanf:5" [fillcolor=lime]
  "Lendo e escrevendo em strings sprintf e sscanf:3" [fillcolor=pink]
  "TKO - Ferramenta de Testes:1" [fillcolor=lime]
  "Seleção Básica:10" [fillcolor=lime]
  "Debugando:1" [fillcolor=pink]
  "Técnicas de seleção I:8" [fillcolor=pink]
  "Técnicas de seleção II:10" [fillcolor=pink]
  "Funções I:5" [fillcolor=lime]
  "Funções II:4" [fillcolor=lime]
  "While:4" [fillcolor=lime]
  "for:8" [fillcolor=lime]
  "Números Aleatórios:3" [fillcolor=lime]
  "IO: argc e argv:2" [fillcolor=pink]
  "Array Iniciante:4" [fillcolor=lime]
  "Array avançado:4" [fillcolor=lime]
  "Array Expert:6" [fillcolor=pink]
  "Strings:6" [fillcolor=lime]
  "Strings II:3" [fillcolor=pink]
  "Ponteiros:1" [fillcolor=lime]
  "Structs:1" [fillcolor=lime]
  "Matrizes:2" [fillcolor=lime]
  "Técnicas em matrizes:1" [fillcolor=pink]
  "Structs Advanced:2" [fillcolor=lime]
  subgraph cluster_Introdução {
    label="Introdução"
    style=filled
    color=lightgray
    "O que são linguagens de programação?:4"
    "Uso do bash:1"
    "Configuração do Ambiente:2"
  }
  subgraph cluster_Básico {
    label="Básico"
    style=filled
    color=lightgray
    "Entrada e Saída - puts, printf, scanf:5"
    "Lendo e escrevendo em strings sprintf e sscanf:3"
    "TKO - Ferramenta de Testes:1"
    "Seleção Básica:10"
  }
}
@enduml
