@startuml graph
skinparam defaultFontName Hasklig
config #lime --> logic #lime
config #lime --> main #lime
main #lime --> access #lime
access #lime --> aggregation #lime
aggregation #lime --> arraylist #lime
arraylist #lime --> arraylist2 #lime
arraylist2 #lime --> arraylist3 #lime
arraylist3 #lime --> map #lime
map #lime --> inheritance #lime
inheritance #lime --> map2 #lime
map2 #lime --> cross #lime
cross #lime --> update #lime
update #lime --> evaluate #lime
evaluate #lime --> draft #lime
draft --> (*)
@enduml