@startuml graph
"[[/o-que-são-linguagens-de-programaçãoO que são linguagens de programação? (0)]]" #lime --> "[[/uso-do-bashUso do bash (1)]]" #pink
"[[/uso-do-bashUso do bash (1)]]" #pink --> "[[/configuração-do-ambienteConfiguração do Ambiente (2)]]" #pink
"[[/o-que-são-linguagens-de-programaçãoO que são linguagens de programação? (0)]]" #lime --> "[[/makefileMakefile (3)]]" #pink
"[[/o-que-são-linguagens-de-programaçãoO que são linguagens de programação? (0)]]" #lime --> "[[/primeiro-códigoPrimeiro código (6)]]" #lime
"[[/entrada-e-saída---puts-printf-scanfEntrada e Saída - puts, printf, scanf (6)]]" #lime --> "[[/stringsStrings (3)]]" #lime
"[[/primeiro-códigoPrimeiro código (6)]]" #lime --> "[[/clean-code---estiloClean Code - Estilo (1)]]" #lime
"[[/primeiro-códigoPrimeiro código (6)]]" #lime --> "[[/clean-code---indentaçãoClean Code - Indentação (1)]]" #lime
"[[/primeiro-códigoPrimeiro código (6)]]" #lime --> "[[/manipulando-tiposManipulando tipos (1)]]" #pink
"[[/primeiro-códigoPrimeiro código (6)]]" #lime --> "[[/casting-e-conversãoCasting e Conversão (2)]]" #pink
"[[/primeiro-códigoPrimeiro código (6)]]" #lime --> "[[/conversãoConversão (0)]]" #pink
"[[/primeiro-códigoPrimeiro código (6)]]" #lime --> "[[/operações-básicasOperações Básicas (3)]]" #lime
"[[/tko---ferramenta-de-testesTKO - Ferramenta de Testes (1)]]" #lime --> "[[/operações-básicasOperações Básicas (3)]]" #lime
"[[/operações-básicasOperações Básicas (3)]]" #lime --> "[[/biblioteca-matemáticaBiblioteca matemática (1)]]" #pink
"[[/operações-básicasOperações Básicas (3)]]" #lime --> "[[/entrada-e-saída---puts-printf-scanfEntrada e Saída - puts, printf, scanf (6)]]" #lime
"[[/stringsStrings (3)]]" #lime --> "[[/lendo-e-escrevendo-em-strings-sprintf-e-sscanfLendo e escrevendo em strings sprintf e sscanf (0)]]" #pink
"[[/whileWhile (3)]]" #lime --> "[[/tratamento-de-erros-de-entrada-fflushTratamento de erros de entrada fflush (0)]]" #pink
"[[/whileWhile (3)]]" #lime --> "[[/macros-include-define-if-ifdef-endifMacros: include, define, if, ifdef, endif (0)]]" #pink
"[[/o-que-são-linguagens-de-programaçãoO que são linguagens de programação? (0)]]" #lime --> "[[/tko---ferramenta-de-testesTKO - Ferramenta de Testes (1)]]" #lime
"[[/entrada-e-saída---puts-printf-scanfEntrada e Saída - puts, printf, scanf (6)]]" #lime --> "[[/seleção-básicaSeleção Básica (10)]]" #lime
"[[/clean-code---estiloClean Code - Estilo (1)]]" #lime --> "[[/seleção-básicaSeleção Básica (10)]]" #lime
"[[/clean-code---indentaçãoClean Code - Indentação (1)]]" #lime --> "[[/seleção-básicaSeleção Básica (10)]]" #lime
"[[/o-que-são-linguagens-de-programaçãoO que são linguagens de programação? (0)]]" #lime --> "[[/debugandoDebugando (1)]]" #pink
"[[/funções-iFunções I (4)]]" #lime --> "[[/técnicas-de-seleção-iTécnicas de seleção I (4)]]" #pink
"[[/técnicas-de-seleção-iTécnicas de seleção I (4)]]" #pink --> "[[/técnicas-de-seleção-iiTécnicas de seleção II (6)]]" #pink
"[[/seleção-básicaSeleção Básica (10)]]" #lime --> "[[/funções-iFunções I (4)]]" #lime
"[[/funções-iFunções I (4)]]" #lime --> "[[/funções-iiFunções II (4)]]" #lime
"[[/seleção-básicaSeleção Básica (10)]]" #lime --> "[[/whileWhile (3)]]" #lime
"[[/whileWhile (3)]]" #lime --> "[[/forfor (4)]]" #lime
"[[/seleção-básicaSeleção Básica (10)]]" #lime --> "[[/números-aleatóriosNúmeros Aleatórios (3)]]" #lime
"[[/números-aleatóriosNúmeros Aleatórios (3)]]" #lime --> "[[/game-zero-a-cemGame Zero a Cem (0)]]" #pink
"[[/funções-iFunções I (4)]]" #lime --> "[[/game-zero-a-cemGame Zero a Cem (0)]]" #pink
"[[/conversãoConversão (0)]]" #pink --> "[[/argc-e-argvargc e argv (1)]]" #pink
"[[/forfor (4)]]" #lime --> "[[/array-inicianteArray Iniciante (3)]]" #lime
"[[/funções-iFunções I (4)]]" #lime --> "[[/array-inicianteArray Iniciante (3)]]" #lime
"[[/array-inicianteArray Iniciante (3)]]" #lime --> "[[/array-avançadoArray avançado (1)]]" #lime
"[[/array-avançadoArray avançado (1)]]" #lime --> "[[/array-expertArray Expert (5)]]" #pink
"[[/array-avançadoArray avançado (1)]]" #lime --> "[[/stringsStrings (3)]]" #lime
"[[/stringsStrings (3)]]" #lime --> "[[/strings-iiStrings II (0)]]" #pink
"[[/ponteirosPonteiros (1)]]" #lime --> "[[/strings-iiStrings II (0)]]" #pink
"[[/strings-iiStrings II (0)]]" #pink --> "[[/strings-expertStrings Expert (1)]]" #pink
"[[/funções-iiFunções II (4)]]" #lime --> "[[/ponteirosPonteiros (1)]]" #lime
"[[/funções-iFunções I (4)]]" #lime --> "[[/structsStructs (2)]]" #lime
"[[/array-inicianteArray Iniciante (3)]]" #lime --> "[[/matrizesmatrizes (2)]]" #lime
"[[/matrizesmatrizes (2)]]" #lime --> "[[/tecnicas-em-matrizestecnicas em matrizes (2)]]" #pink
"[[/merged-tecniquemerged tecnique (2)]]" #lime --> "[[/tecnicas-em-matrizestecnicas em matrizes (2)]]" #pink
"[[/ponteirosPonteiros (1)]]" #lime --> "[[/merged-tecniquemerged tecnique (2)]]" #lime
"[[/array-inicianteArray Iniciante (3)]]" #lime --> "[[/merged-tecniquemerged tecnique (2)]]" #lime
"[[/structsStructs (2)]]" #lime --> "[[/merged-tecniquemerged tecnique (2)]]" #lime
"[[/seleção-básicaSeleção Básica (10)]]" #lime --> "[[/aula-24---enumAula 24 - enum (2)]]" #lime
"[[/ponteirosPonteiros (1)]]" #lime --> "[[/ponteiros-iiPonteiros ii (2)]]" #pink
"[[/ponteirosPonteiros (1)]]" #lime --> "[[/alocação-dinâmicaAlocação Dinâmica (0)]]" #pink
"[[/alocação-dinâmicaAlocação Dinâmica (0)]]" #pink --> "[[/alocação-dinâmicaAlocação Dinâmica (2)]]" #pink
"[[/ponteiros-iiPonteiros ii (2)]]" #pink --> "[[/arquivos-textoarquivos texto (1)]]" #lime
"[[/arquivos-textoarquivos texto (1)]]" #lime --> "[[/arquivos-binarioarquivos binario (1)]]" #pink
"[[/arquivos-textoarquivos texto (1)]]" #lime -> (*)
@enduml