@startuml graph
skinparam defaultFontName Hasklig
tools_basic #lime --> tools_bash #yellow
tools_bash #yellow --> tools_local_ide #yellow
tools_basic #lime --> tools_makefile #yellow
tools_basic #lime --> types_basic #lime
io_basic #lime --> string_basic #lime
types_basic #lime --> style_guide #lime
types_basic #lime --> style_indentation #lime
types_basic #lime --> types_modifiers #yellow
types_basic #lime --> types_casting #yellow
types_basic #lime --> types_conversion #yellow
types_basic #lime --> types_operations #lime
tools_tko #lime --> types_operations #lime
types_operations #lime --> tools_math.h #yellow
types_operations #lime --> io_basic #lime
string_novice #lime --> io_string #yellow
repeat_novice #lime --> io_error #yellow
repeat_novice #lime --> tools_macros #yellow
tools_basic #lime --> tools_tko #lime
tools_basic #lime --> tools_debug #yellow
io_basic #lime --> select_novice #yellow
functions_novice #lime --> select_advanced #yellow
select_novice #yellow --> select_expert #yellow
select_expert #yellow --> functions_novice #lime
functions_novice #lime --> function_advanced #lime
select_novice #yellow --> repeat_novice #lime
repeat_novice #lime --> repeat_advanced #lime
select_novice #yellow --> tools_rand #lime
tools_rand #lime --> game_zero_cem #lime
functions_novice #lime --> game_zero_cem #lime
types_conversion #yellow --> io_argc_argv #lime
repeat_advanced #lime --> array_novice #lime
functions_novice #lime --> array_novice #lime
array_novice #lime --> array_advanced #lime
tools_rand #lime --> game_blackjack #lime
array_advanced #lime --> game_blackjack #lime
array_advanced #lime --> array_expert #lime
array_advanced #lime --> string_novice #lime
string_novice #lime --> string_advanced #lime
pointers_novice #lime --> string_advanced #lime
string_advanced #lime --> string_expert #lime
function_advanced #lime --> pointers_novice #lime
functions_novice #lime --> structs_novice #lime
array_novice #lime --> matrix_novice #lime
matrix_novice #lime --> matrix_advanced #lime
structs_advanced #lime --> matrix_advanced #lime
tools_rand #lime --> game_jogodavida #lime
matrix_advanced #lime --> game_jogodavida #lime
tools_rand #lime --> game_cobrinha #lime
structs_advanced #lime --> game_cobrinha #lime
select_novice #yellow --> enum #lime
pointers_novice #lime --> pointers_advanced #lime
pointers_novice #lime --> memory_novice #lime
memory_novice #lime --> memory_advanced #lime
pointers_advanced #lime --> files_novice #lime
files_novice #lime --> files_advanced #lime
pointers_novice #lime --> structs_advanced #lime
array_novice #lime --> structs_advanced #lime
structs_novice #lime --> structs_advanced #lime
structs_advanced --> (*)
@enduml