@startuml graph
"tools_basic (0)" #lime --> "[[http://google.com tools_bash (1)]]"  #pink
"tools_bash (1)" #pink --> "tools_local_ide (2)" #pink
"tools_basic (0)" #lime --> "tools_makefile (3)" #pink
"tools_basic (0)" #lime --> "types_basic (7)" #lime
"types_basic (7)" #lime --> "style_guide (1)" #lime
"types_basic (7)" #lime --> "style_indentation (1)" #lime
"types_basic (7)" #lime --> "types_modifiers (1)" #pink
"types_basic (7)" #lime --> "types_casting (2)" #pink
"types_basic (7)" #lime --> "types_conversion (0)" #pink
"types_basic (7)" #lime --> "types_operations (3)" #lime
"tools_tko (1)" #lime --> "types_operations (3)" #lime
"types_operations (3)" #lime --> "tools_math.h (1)" #pink
"types_operations (3)" #lime --> "io_basic (6)" #lime
"string_novice (3)" #lime --> "io_string (0)" #pink
"repeat_novice (3)" #lime --> "io_error (0)" #pink
"repeat_novice (3)" #lime --> "tools_macros (0)" #pink
"tools_basic (0)" #lime --> "tools_tko (1)" #lime
"io_basic (6)" #lime --> "select_novice (10)" #lime
"style_guide (1)" #lime --> "select_novice (10)" #lime
"style_indentation (1)" #lime --> "select_novice (10)" #lime
"tools_basic (0)" #lime --> "tools_debug (1)" #pink
"functions_novice (4)" #lime --> "select_advanced (4)" #pink
"select_advanced (4)" #pink --> "select_expert (6)" #pink
"select_novice (10)" #lime --> "functions_novice (4)" #lime
"functions_novice (4)" #lime --> "function_advanced (4)" #lime
"select_novice (10)" #lime --> "repeat_novice (3)" #lime
"repeat_novice (3)" #lime --> "repeat_advanced (4)" #lime
"select_novice (10)" #lime --> "tools_rand (3)" #lime
"tools_rand (3)" #lime --> "game_zero_cem (0)" #pink
"functions_novice (4)" #lime --> "game_zero_cem (0)" #pink
"types_conversion (0)" #pink --> "io_argc_argv (1)" #pink
"repeat_advanced (4)" #lime --> "array_novice (3)" #lime
"functions_novice (4)" #lime --> "array_novice (3)" #lime
"array_novice (3)" #lime --> "array_advanced (1)" #lime
"array_advanced (1)" #lime --> "array_expert (5)" #pink
"array_advanced (1)" #lime --> "string_novice (3)" #lime
"string_novice (3)" #lime --> "string_advanced (0)" #pink
"pointers_novice (1)" #lime --> "string_advanced (0)" #pink
"string_advanced (0)" #pink --> "string_expert (1)" #pink
"function_advanced (4)" #lime --> "pointers_novice (1)" #lime
"functions_novice (4)" #lime --> "structs_novice (2)" #lime
"array_novice (3)" #lime --> "matrix_novice (2)" #lime
"matrix_novice (2)" #lime --> "matrix_advanced (2)" #pink
"structs_advanced (2)" #lime --> "matrix_advanced (2)" #pink
"pointers_novice (1)" #lime --> "structs_advanced (2)" #lime
"array_novice (3)" #lime --> "structs_advanced (2)" #lime
"structs_novice (2)" #lime --> "structs_advanced (2)" #lime
"select_novice (10)" #lime --> "enum (2)" #lime
"pointers_novice (1)" #lime --> "pointers_advanced (2)" #pink
"pointers_novice (1)" #lime --> "memory_novice (0)" #pink
"memory_novice (0)" #pink --> "memory_advanced (2)" #pink
"pointers_advanced (2)" #pink --> "files_novice (1)" #lime
"files_novice (1)" #lime --> "files_advanced (1)" #pink
"files_novice (1)" #lime -> (*)
@enduml